-- MySQL Script generated by MySQL Workbench
-- Wed Mar  8 14:36:28 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kipao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kipao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kipao` DEFAULT CHARACTER SET utf8 ;
USE `kipao` ;

-- -----------------------------------------------------
-- Table `kipao`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kipao`.`produtos` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kipao`.`localizacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kipao`.`localizacoes` (
  `id` INT NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kipao`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kipao`.`clientes` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `localizacao_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_clientes_localizacao1_idx` (`localizacao_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kipao`.`lojas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kipao`.`lojas` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `localizacao_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lojas_localizacao1_idx` (`localizacao_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kipao`.`vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kipao`.`vendedores` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kipao`.`datas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kipao`.`datas` (
  `id` INT NOT NULL,
  `data` DATE NOT NULL,
  `ano` CHAR(4) NOT NULL,
  `mes` CHAR(4) NOT NULL,
  `dia` CHAR(4) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kipao`.`vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kipao`.`vendas` (
  `id` INT NOT NULL,
  `produto_id` INT NOT NULL,
  `vendedor_id` INT NOT NULL,
  `loja_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  `data_id` INT NOT NULL,
  `valor` DECIMAL(11,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vendas_produtos_idx` (`produto_id` ASC),
  INDEX `fk_vendas_lojas1_idx` (`loja_id` ASC),
  INDEX `fk_vendas_clientes1_idx` (`cliente_id` ASC),
  INDEX `fk_vendas_vendedores1_idx` (`vendedor_id` ASC),
  INDEX `fk_vendas_datas1_idx` (`data_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kipao`.`consumo_agua`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kipao`.`consumo_agua` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `loja_id` INT NOT NULL,
  `data_id` INT NOT NULL,
  `valor` DECIMAL(11,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_consumo_agua_lojas1_idx` (`loja_id` ASC),
  INDEX `fk_consumo_agua_datas1_idx` (`data_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
